import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "syedowais02-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en" className="h-full">
       <body >
        <div  className="grid-bg"/> {/* Fixed background layer */}
        {/* Foreground content */}
          {children}
      
      </body>
    </html>
  );
}
